version: '3.8'

services:
  web:
    build: .
    restart: always
    command: gunicorn -w 5 -b 0.0.0.0:8015 config.wsgi
    volumes:
      - .:/usr/app/
    ports:
      - 8015:8015
  celery:
    build: .
    restart: always
    command: celery -A config worker --loglevel=INFO --concurrency=10 -n worker_dokr
    volumes:
      - .:/usr/app/
  celery-beat:
    build: .
    restart: always
    command: celery -A config beat --loglevel=INFO
    volumes:
      - .:/usr/app/